version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-north-1:274201610284:task-definition/pension-details-task:1"
        LoadBalancerInfo:
          ContainerName: "pension-details-container"
          ContainerPort: "9097"
        PlatformVersion: "LATEST"