version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 274201610284.dkr.ecr.eu-north-1.amazonaws.com
    - IMAGE_NAME=pension-details-repo-913044
    - IMAGE_URI=274201610284.dkr.ecr.eu-north-1.amazonaws.com/pension-details-repo-913044:latest
    - CONTAINER_NAME=pension-details-container
  build:
    commands:
    - echo Build started on `date`
    - echo $IMAGE_URI
    - mvn clean package -Ddockerfile.skip
    - docker build --tag $IMAGE_URI .
  post_build:
    commands:
    - printenv
    - echo Build completed on `date`
    - echo $(docker images)
    - echo Pushing docker image
    - docker push $IMAGE_URI
    - echo push completed
    - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $IMAGE_URI > imagedefinitions.json
artifacts:
  files:
  - imagedefinitions.json